# Generated by Django 6.0.6 on 2026-06-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=50)),
                ('player_type', models.CharField(choices=[('skater', 'Skater'), ('goalie', 'Goalie')], max_length=10)),
                ('points_per_unit', models.FloatField()),
            ],
            options={
                'unique_together': {('stat_name', 'player_type')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('C', 'Centre'), ('L', 'Left Wing'), ('R', 'Right Wing'), ('D', 'Defence'), ('G', 'Goalie')], max_length=2)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('date', models.DateField(db_index=True)),
                ('game_type', models.IntegerField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final')], db_index=True, default='scheduled', max_length=20)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='GoalieStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Loss'), ('O', 'OT Loss')], max_length=1, null=True)),
                ('toi', models.IntegerField(default=0)),
                ('shots_against', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('save_pct', models.FloatField(blank=True, null=True)),
                ('pim', models.IntegerField(default=0)),
                ('fantasy_points', models.FloatField(db_index=True, default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalie_stats', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalie_stats', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['game'], name='core_goalie_game_id_b470c2_idx')],
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='SkaterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('plus_minus', models.IntegerField(default=0)),
                ('pim', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('power_play_goals', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('faceoff_pct', models.FloatField(blank=True, null=True)),
                ('toi', models.IntegerField(default=0)),
                ('blocked_shots', models.IntegerField(default=0)),
                ('shifts', models.IntegerField(default=0)),
                ('giveaways', models.IntegerField(default=0)),
                ('takeaways', models.IntegerField(default=0)),
                ('fantasy_points', models.FloatField(db_index=True, default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skater_stats', to='core.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skater_stats', to='core.player')),
            ],
            options={
                'indexes': [models.Index(fields=['game'], name='core_skater_game_id_a0eab5_idx'), models.Index(fields=['player', 'fantasy_points'], name='core_skater_player__b1f014_idx')],
                'unique_together': {('player', 'game')},
            },
        ),
    ]
