# Generated by Django 6.0.6 on 2026-06-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalieScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(choices=[('saves', 'Saves'), ('goals_against', 'Goals Against'), ('shots_against', 'Shots Against'), ('win', 'Win'), ('ot_loss', 'OT Loss')], max_length=50, unique=True)),
                ('points_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SkaterScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(choices=[('goals', 'Goals'), ('assists', 'Assists'), ('shots', 'Shots on Goal'), ('hits', 'Hits'), ('plus_minus', 'Plus/Minus'), ('pim', 'Penalty Minutes'), ('power_play_goals', 'Power Play Goals'), ('blocked_shots', 'Blocked Shots'), ('takeaways', 'Takeaways'), ('giveaways', 'Giveaways')], max_length=50, unique=True)),
                ('points_per_unit', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScoringRule',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('C', 'Centre'), ('L', 'Left Wing'), ('R', 'Right Wing'), ('D', 'Defense'), ('G', 'Goalie')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date', 'status'], name='core_game_date_7b6853_idx'),
        ),
    ]
