# Generated by Django 6.0.6 on 2026-06-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_scoring_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Pipeline Control',
                'verbose_name_plural': 'Pipeline Control',
                'managed': False,
            },
        ),
    ]
